spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/games_loot_shop_db
    username: postgres
    password: postgre123

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mail:
    host: smtp.mail.ru
    port: 465
    username: mitka.2002@mail.ru
    password: ahf6MxAtPSER2fqve1ps
    protocol: smtp


upload:
  path: Q:/images


